---
title: "P8130: Biostats I - Final Project"
author: "Daniel Ojeranti, David Nemirovsky, Ford Holland, Jared Klug, Justin Vargas"
date: "12/18/2020"
output: github_document
---

```{r setup, include = F}
library(tidyverse)
library(corrplot)
library(leaps)
library(HH)
library(modelr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

knitr::knit_hooks$set(inline = as.character)
```

Read and tidy data:

```{r read dataset, message = F, warning = F}
hate_crimes_df = 
  read_csv("./HateCrimes.csv") %>% 
  mutate(
    unemployment = as.factor(unemployment), 
    urbanization = as.factor(urbanization),
    hate_crimes_per_100k_splc = as.numeric(hate_crimes_per_100k_splc)
  ) %>% 
  drop_na()
```

EDA:

```{r distribution of hate crimes, message = F}
hate_crimes_df %>% 
  ggplot(aes(x = hate_crimes_per_100k_splc)) + 
  geom_histogram()
```

Variable Selection:

```{r variable selection}
par(mar = c(4,5,1,1))
corr_data = 
  hate_crimes_df %>% 
  dplyr::select(- unemployment, - urbanization, - state)
cor(corr_data[,c(1:5)]) %>%  
  corrplot(method = "circle", type = "upper", diag = FALSE)

# Potential multicollinearity btwn perc_non_white and perc_non_citizen

model_1 = lm(hate_crimes_per_100k_splc ~ unemployment + urbanization + median_household_income + perc_population_with_high_school_degree + perc_non_citizen + gini_index + perc_non_white, data = hate_crimes_df)

summary(model_1)

# Remove perc_non_white

model_2 = lm(hate_crimes_per_100k_splc ~ unemployment + urbanization + median_household_income + perc_population_with_high_school_degree + perc_non_citizen + gini_index, data = hate_crimes_df)

summary(model_2)

# Remove unemployment

model_3 = lm(hate_crimes_per_100k_splc ~ urbanization + median_household_income + perc_population_with_high_school_degree + perc_non_citizen + gini_index, data = hate_crimes_df)

summary(model_3)

# Remove median household income

model_4 = lm(hate_crimes_per_100k_splc ~ urbanization + perc_population_with_high_school_degree + perc_non_citizen + gini_index, data = hate_crimes_df)

summary(model_4)

# Remove urbanization

model_5 = lm(hate_crimes_per_100k_splc ~ perc_population_with_high_school_degree + perc_non_citizen + gini_index, data = hate_crimes_df)

summary(model_5)

# Remove perc_non_citizen

model_6 = lm(hate_crimes_per_100k_splc ~ perc_population_with_high_school_degree + gini_index, data = hate_crimes_df)

summary(model_6)

# cleaner method for backwards selection

model_all = lm(hate_crimes_per_100k_splc ~ . - state, data = hate_crimes_df)
summary(model_all)

step_1 = update(model_all, . ~ . - perc_non_white)
summary(step_1)

step_2 = update(step_1, . ~ . - unemployment)
summary(step_2)

step_3 = update(step_2, . ~ . - median_household_income)
summary(step_3)

step_4 = update(step_3, . ~ . - urbanization)
summary(step_4)

model_fin = update(step_4, . ~ . - perc_non_citizen)
summary(model_fin)

# try using stepwise

model_untrans = step(model_all, direction = "backward")
summary(model_untrans)
plot(model_untrans)
```

Q-Q Plots:

```{r qq plots}
# Non-transformed

par(mfrow = c(2,2))
plot(model_fin)
```

Transformed:

```{r transformed}
library(MASS)
boxcox(model_fin)

# Natural log transformation:

hate_crimes_trans = 
  hate_crimes_df %>% 
  mutate(ln_hate_crimes = log(hate_crimes_per_100k_splc))

model_all_trans = lm(ln_hate_crimes ~ . - state - hate_crimes_per_100k_splc, data = hate_crimes_trans)
summary(model_all_trans)

# using stepwise

model_trans = step(model_all_trans, direction = "backward")
summary(model_trans)

# QQ plots

par(mfrow = c(2,2))
trans_qq = plot(model_trans)
untrans_qq = plot(model_fin)
```

Remove influential point:

```{r remove DC}
hate_crimes_no_out = 
  hate_crimes_df %>% 
  filter(state != "District of Columbia")

model_untrans_no_out = lm(hate_crimes_per_100k_splc ~ . - state, data = hate_crimes_no_out)
summary(model_untrans_no_out)

model_untrans_adj = step(model_untrans_no_out, direction = "backward")
summary(model_untrans_adj)

plot(model_untrans_adj)
```

Remove Infl//out in Transformed

```{r}
hate_crimes_no_out = 
  hate_crimes_trans %>% 
  filter(state != "District of Columbia")

model_all_trans = lm(ln_hate_crimes ~ . - state - hate_crimes_per_100k_splc, data = hate_crimes_trans)
summary(model_all_trans)

step_1_trans = update(model_all_trans, . ~ . - perc_non_white)
summary(step_1_trans)

step_2_trans = update(step_1_trans, . ~ . - unemployment)
summary(step_2_trans)

step_3_trans = update(step_2_trans, . ~ . - median_household_income)
summary(step_3_trans)

step_4_trans = update(step_3_trans, . ~ . - urbanization)
summary(step_4_trans)

model_trans_no_out = update(step_4_trans, . ~ . - perc_non_citizen)
summary(model_trans_no_out)

plot(model_trans_no_out)
```

Compare everything we have so far:

```{r}
plot(model_untrans)
plot(model_untrans_adj)
plot(model_trans)
```

New Box Cox:

```{r}
library(MASS)

hate_crimes_no_dc = 
  hate_crimes_df %>% 
  filter(state != "District of Columbia")

model_adj_all = lm(hate_crimes_per_100k_splc ~ . - state, data = hate_crimes_no_dc)
summary(model_adj_all)

model_adj = step(model_adj_all, direction = "backward")
summary(model_adj)
plot(model_adj)

boxcox(model_adj)

model_adj_no_dc = lm(hate_crimes_per_100k_splc ~ perc_population_with_high_school_degree  + unemployment * gini_index, data = hate_crimes_no_dc)
summary(model_adj_no_dc)
plot(model_adj_no_dc)
```

No Alaska:

```{r}
hate_crimes_no_dc_ak = 
  hate_crimes_no_dc %>% 
  filter(state != "Oregon")

# R-sq for no DC/AK is 0.3529

par(mfrow = c(2,2))
model_adj_no_dc_ak = lm(hate_crimes_per_100k_splc ~ perc_population_with_high_school_degree + gini_index + unemployment, data = hate_crimes_no_dc_ak)
summary(model_adj_no_dc_ak)
plot(model_adj_no_dc_ak)
vif(model_adj_no_dc_ak)

# Take out a bunch of more states -> R-sq is 0.3614

hate_crimes_no_extra = 
  hate_crimes_no_dc %>% 
  filter(state != "Alaska") %>% 
  filter(state != "New Jersey") %>% 
  filter(state != "California") %>% 
  filter(state != "Washington") %>% 
  filter(state != "Minnesota") %>% 
  filter(state != "Oregon") %>% 
  filter(state != "New York")

model_adj_no_extra = lm(hate_crimes_per_100k_splc ~ perc_population_with_high_school_degree + gini_index * unemployment, data = hate_crimes_no_extra)
summary(model_adj_no_extra)
plot(model_adj_no_extra)
vif(model_adj_no_extra)
```

Transformed no DC/AK:

```{r}
# Use what Cody said:
hate_crimes_trans_no_dc_or = 
  hate_crimes_trans %>% 
  filter(state != "District of Columbia") %>% 
  filter(state != "Oregon")

# Plot for R2 and Cp vs parameters

subsets = regsubsets(ln_hate_crimes ~ . - state - hate_crimes_per_100k_splc, data = hate_crimes_trans_no_dc_or)
rs = summary(subsets)
par(mar = c(4,4,1,1))
par(mfrow = c(1,2))
plot(2:8, rs$cp, xlab = "No of parameters", ylab = "Cp Statistic")
abline(0,1)
plot(2:8, rs$adjr2, xlab = "No of parameters", ylab = "Adj R2")

hate_crimes_trans_no_dc_ak$state[42]

par(mfrow = c(2,2))
model_adj_trans_no_dc_or = lm(ln_hate_crimes ~ perc_population_with_high_school_degree + gini_index + unemployment, data = hate_crimes_trans_no_dc_or)
summary(model_adj_trans_no_dc_or)
plot(model_adj_trans_no_dc_or)
vif(model_adj_trans_no_dc_or)

stu_res = rstandard(model_adj_trans_no_dc_ak)
stu_res[abs(stu_res) > 2]

#stratified by Low Unemployment b/c interaction term significant
hate_crimes_trans_no_dc_ak_low = 
  hate_crimes_trans %>% 
  filter(state != "District of Columbia") %>% 
  filter(state != "Oregon") %>% 
  filter(unemployment == "low")

par(mfrow = c(2,2))
model_adj_trans_no_dc_ak_low = lm(ln_hate_crimes ~ perc_population_with_high_school_degree + gini_index, data = hate_crimes_trans_no_dc_ak_low)
summary(model_adj_trans_no_dc_ak_low)
plot(model_adj_trans_no_dc_ak_low)
vif(model_adj_trans_no_dc_ak_low)

#Stratified by High Unemployment

hate_crimes_trans_no_dc_ak_high = 
  hate_crimes_trans %>% 
  filter(state != "District of Columbia") %>% 
  filter(state != "Oregon") %>% 
  filter(unemployment == "high")

par(mfrow = c(2,2))
model_adj_trans_no_dc_ak_high = lm(ln_hate_crimes ~ perc_population_with_high_school_degree + gini_index, data = hate_crimes_trans_no_dc_ak_high)
summary(model_adj_trans_no_dc_ak_high)
plot(model_adj_trans_no_dc_ak_high)
vif(model_adj_trans_no_dc_ak_high)
```
