---
title: "Descrptive statistics"
date: "12/13/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gtsummary)
library(arsenal)
```

```{r}
# read hate crimes data and format categorical variables for tables 
df_hc <- 
  read_csv("HateCrimes.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    hate_crimes = as.numeric(hate_crimes_per_100k_splc),
    unemp = unemployment %>% str_to_title() %>% factor(levels = c("Low", "High")),
    urban = urbanization %>% str_to_title() %>% factor(levels = c("Low", "High"))
  ) 

# check derivations
df_hc %>% count(unemp, unemployment)
df_hc %>% count(urban, urbanization)

# select parsed fields
df_hc <- 
  df_hc %>% 
  select(-c(unemployment, urbanization, hate_crimes_per_100k_splc))

# look at summary
skimr::skim(df_hc)
summary(df_hc$hate_crimes)
```

## Plot hate crime distribution

```{r}
# plot distribution of hate crimes data
df_hc %>% 
  ggplot(aes(x = hate_crimes)) +
  geom_histogram(aes(y = ..density..), alpha = 0.5) +
  geom_density(aes(), alpha = 0.5) +
  labs(
    title = "Distribution of hate crimes",
    x = "Hate crimes per 100k population",
    y = "Density"
  )
```

## Descriptive statistics

```{r}
# using gtsummary
df_hc %>% 
  select(hate_crimes, everything()) %>% 
  mutate(
    perc_population_with_high_school_degree = perc_population_with_high_school_degree*100,
    perc_non_citizen = perc_non_citizen*100,
    perc_non_white = perc_non_white*100
  ) %>% 
  tbl_summary(
    include = -c(state),
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{mean} ({sd})",
                                     "{median} ({p25}, {p75})", 
                                     "{min}, {max}"),
    label = 
      list(
        hate_crimes ~ "Hate crimes (per 100k population)",
        median_household_income ~ "Median household income",
        perc_population_with_high_school_degree ~ "Percent population with high school degree",
        perc_non_citizen ~ "Percent non-citizen",
        gini_index ~ "Gini index",
        perc_non_white ~ "Percent non-white",
        unemp ~ "Unemployment",
        urban ~ "Urbanization"
      )
  ) %>% 
  modify_footnote(starts_with("stat_") ~ NA)

```


## Check associations

```{r}
# education
df_hc %>% 
  ggplot(aes(x = perc_population_with_high_school_degree, y = hate_crimes)) +
  geom_point() +
  geom_smooth(method = lm)

# income
df_hc %>% 
  ggplot(aes(x = median_household_income, y = hate_crimes)) +
  geom_point() +
  geom_smooth(method = lm)

# percent non-citizen
df_hc %>% 
  ggplot(aes(x = perc_non_citizen, y = hate_crimes)) +
  geom_point() +
  geom_smooth(method = lm)

# GINI index
df_hc %>% 
  ggplot(aes(x = gini_index, y = hate_crimes)) +
  geom_point() +
  geom_smooth(method = lm)

# percent non-white
df_hc %>% 
  ggplot(aes(x = perc_non_white, y = hate_crimes)) +
  geom_point() +
  geom_smooth(method = lm)
```

